//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.Templates {
    
    
    public partial class Template_Two_Two {
        
        /// <summary>
        /// titleLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label titleLabel;
        
        /// <summary>
        /// dsucBottomLeft control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DataVisualization.UserControls.DashboardSectionUserControl dsucBottomLeft;
        
        /// <summary>
        /// dsucBottomRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DataVisualization.UserControls.DashboardSectionUserControl dsucBottomRight;
    }
}
